### ISSUE TITLE
Window title is not center aligned in Cinnamon

### ISSUE THREAD

**Issue by lqmanh** [LinxGem33/OSX-Arc-White#11] opened 2017-02-12 09:24 UTC
I am using Cinnamon 3.2 and having this issue.
![screenshot from 2017-02-12 16-10-50](https://cloud.githubusercontent.com/assets/20436482/22860930/43d3ccae-f13e-11e6-8fa9-5442addc2c27.png)
As you can see, the text "Themes" is a bit deflected to the left.

**Comment by LinxGem33** [comment] 2017-02-14 02:06
@lqmanh 

appreciate the feed back Ill investigate the issue and report back but i don't think this is a issue with the theme, i think i know what the issue is but just to make sure ill double check. 

kind regards

**Comment by LinxGem33** [comment] 2017-03-04 17:20
@lqmanh 

please could you test the latest release and see if the issue has been resolved and report back your findings.

kind regards

**Comment by lqmanh** [comment] 2017-03-06 15:35
Thanks for your efforts, but it still doesn't seem to be working.

**Comment by LinxGem33** [comment] 2017-03-07 12:38
@lqmanh 

thanks for letting me know.

kind regards

**Comment by Elbullazul** [comment] 2017-03-08 20:33
@lqmanh this is an easy fix, but doesn't guarantee it's bug free:

replace the original code ```xml
	

<draw_ops name="title_focused">
	<title x="(0 `max` ((width - title_width) / 2)) + 2"
               y="(0 `max` ((height - title_height) / 2)) + 1"
               color="C_title_focused" />
</draw_ops>

<draw_ops name="title_unfocused">
	<title x="(0 `max` ((width - title_width) / 2)) + 2"
               y="(0 `max` ((height - title_height) / 2)) + 1"
               color="C_title_unfocused"/>
</draw_ops>
```

with ```xml
	<!-- title -->

<draw_ops name="title_focused">
	<title x="(width - title_width) / 2)"
               y="(0 `max` ((height - title_height) / 2)) + 1"
               color="C_title_focused" />
</draw_ops>

<draw_ops name="title_unfocused">
	<title x="(width - title_width) / 2)"
               y="(0 `max` ((height - title_height) / 2)) + 1"
               color="C_title_unfocused"/>
</draw_ops>
```

**Comment by JontySR** [comment] 2017-03-21 18:44
I also have this problem, and the fix from @Elbullazul didn't work for me.

**Comment by LinxGem33** [comment] 2017-04-05 15:14
@lqmanh 
going to close this issue as @Elbullazul  has the correct fix.

**Closed by LinxGem33** 2017-04-05 15:14 UTC

**Comment by nick-s-b** [comment] 2017-09-18 17:11
@LinxGem33 could you please update the main branch with this change please?
